### ISSUE TITLE
Attribute database_type missing

### ISSUE THREAD

**Issue by veritazx** [zms-publishing/Products.ZMySQLDA#12]
Python 2.7.15, Zope 2.13.27: Tests green. Adapter is working, but not as drop-in-replacement:
- our Products were reading an attribute database_type (DA.py), that vanished.

I didn't find any other maintained DAs (Postgres etc.) and the attribute seems to have been a copy/paste thing that is not part of any spec. I wouldn't mind if it stays lost.

**Comment by dataflake** [comment]
As you already noted, this was just an internal variable and not part of any official API. You should not have relied in that in the first place. Closing as `wontfix`.
