### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by dataflake** [zms-publishing/Products.ZMySQLDA#2]
@rbu IMHO we are ready for at least a beta release. Do you see any issue with that?

**Comment by rbu** [comment]
Looks very good from my side, thanks for all the cleanup, docs and tests. That's impressive. Do you want to go ahead with the release?

**Comment by dataflake** [comment]
Yeah, I'll do a beta1. That way no one who is set to pull stable releases can get hurt.

**Comment by dataflake** [comment]
https://pypi.org/project/Products.ZMySQLDA/4.0b1/
