### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by dataflake** [zms-publishing/Products.ZMySQLDA#3]
@rbu We're missing Travis CI integration, which I can't do myself because it requires GitHub organization-level access to e.g. list an organization's repositories. Could you set that up?

**Comment by dataflake** [comment]
P.S.: a ``.travis.yml`` is already in place.

**Comment by dwt** [comment]
yup, will probably do today.

**Comment by rbu** [comment]
It's set up: https://travis-ci.org/zms-publishing/Products.ZMySQLDA/
