### ISSUE TITLE
Beta testing required

### ISSUE THREAD

**Issue by dataflake** [zms-publishing/Products.ZMySQLDA#4]
Now that version 4.0b1 is on PyPI it's easy to start testing it.

The goal for 4.0 is to be a drop-in replacement for previous 3.x versions, and full compatibility with Both Zope 2.13 with Python 2.7 and Zope 4 with Python 2.7, 3.5 and 3.6. You should be able to take any existing setup under Zope 2.13 or 4 and specify version 4.0b1 for the Products.ZMySQLDA egg and it should just work.

Some manual testing showed me that the ``mysqlclient`` library can have a query performance penalty of up to 8% compared to the obsolete MySQLdb1. That's most likely due to string handling for Python2/3 compatibility. YMMV.

If any errors show up where there are none under ZMySQLDA 3.x then that's a bug and should be posted to the issue tracker here.

**Comment by rbu** [comment]
@dataflake Did you attempt a conversion of an existing Py2/Zope2 ZODB to Py3/Zope4 with this product yet? At the last sprint, we used [zodbupdate](https://pypi.org/project/zodbupdate/) for the conversion, but possibly this product needs an entry point for existing saved ```str``` instances. I haven't checked that yet.

**Comment by dataflake** [comment]
@rbu I did not, and since it is so easy to just delete and recreate the database adapter in the ZODB I'm not going to spend time on it. If someone else wants to work on it, feel free.

**Comment by dataflake** [comment]
Version 4.0 is now live on https://pypi.org/project/Products.ZMySQLDA/ so I'll close this issue.
