### ISSUE TITLE
MariaDB >= 10.0 compatibility

### ISSUE THREAD

**Issue by veritazx** [zms-publishing/Products.ZMySQLDA#7]
Hi there! 
It is marvelous, that you are now actively maintaining the DA. 
I had contacted John Eikenberry and volunteered a year ago but was then sidetracked by my private life. I only managed to fork the Adapter and add our necessary fixes, but didn't take over and didn't put anything on PyPI.
Now for the issue: 
The savepoint method checks for version compatibility based on a version string. Comparing '5.0.2' <= '10.0.1' or similar does not return True. Solution: use version tuples. 
I'd like to cherrypick our solution and PR it here. Is that okay?

I'll also add another issue and will try to help with the beta testing. We have two Applications running on Py2, Z2, Plone 4 using ZMySQLDA, which will be made py3-ready in the next months and could be used for beta testing. 

Thanks and bye, 

Peter

**Comment by dataflake** [comment]
Instead of asking please just submit a PR
