### ISSUE TITLE
The default connect timeout is fairly large

### ISSUE THREAD

**Issue by veritazx** [zms-publishing/Products.ZMySQLDA#8]
Hi again, 
we ran into problems when server communication to our database server breaks down. The Zope Frontends keep on delivering the normal web content. But as soon as someone tries to vitit the mysql-based application, they send one frontend after the other into oblivion because of the really huge connection timeout. 

Superb solution: Make the timeout configurable
Not so supberb solution: Set a somewhat more reasonable timeout (e.g. 3 seconds).

I'd again supply the solution and PR it directly, if approved.

Thanks a lot!

Peter

**Comment by dataflake** [comment]
Instead of asking please just submit a PR

**Comment by dataflake** [comment]
Fixed by #10
